In [15]:
# --- Sistema de Recomendação por Similaridade de Cosseno: 
# O modelo utiliza uma matriz para verificar a congruência em que dois produtos são vendidos na mesma compra ---
# Objetivo: Recomendação de produto para clientes novos.
# O arquivo segue uma organização de arquivos /cos_similaridade.ipynb
# /datasets/vendas_2023_2024.csv

# Importação das bibliotecas pandas para manipular dados e sklearn para construção da matriz
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# Leitura do .csv de vendas
df = pd.read_csv('datasets/vendas_2023_2024.csv')

In [16]:
# Construção e Exibição da matriz comparando clientes e produtos
matriz = pd.crosstab(df['id_client'], df['id_product'])
matriz.head()

id_product,1,2,3,4,5,6,7,8,9,10,...,141,142,143,144,145,146,147,148,149,150
id_client,,,,,,,,,,,,,,,,,,,,,
1,2,0,3,3,1,4,0,0,0,0,...,1,1,0,4,2,2,1,2,0,0
2,0,2,1,0,1,1,2,2,2,2,...,2,1,4,2,1,3,0,2,1,2
3,1,3,1,3,2,2,1,0,1,1,...,0,2,2,2,0,1,1,1,1,1
4,2,2,0,3,3,0,1,0,0,2,...,1,1,2,1,0,0,2,0,2,2
5,1,3,0,2,1,2,1,1,2,4,...,3,1,1,1,0,3,1,1,2,0

In [17]:
# Alteração de valores quantitativos para True ou False, usando 1 e 0
matriz_presenca = (matriz > 0).astype(int)
matriz_presenca.head()

id_product,1,2,3,4,5,6,7,8,9,10,...,141,142,143,144,145,146,147,148,149,150
id_client,,,,,,,,,,,,,,,,,,,,,
1,1,0,1,1,1,1,0,0,0,0,...,1,1,0,1,1,1,1,1,0,0
2,0,1,1,0,1,1,1,1,1,1,...,1,1,1,1,1,1,0,1,1,1
3,1,1,1,1,1,1,1,0,1,1,...,0,1,1,1,0,1,1,1,1,1
4,1,1,0,1,1,0,1,0,0,1,...,1,1,1,1,0,0,1,0,1,1
5,1,1,0,1,1,1,1,1,1,1,...,1,1,1,1,0,1,1,1,1,0

In [18]:
# Fórmula para cálculo de similaridade na matriz
similarity = cosine_similarity(matriz_presenca.T)

In [19]:
# Formatação e Exibição dos valores de similaridades
df_similarity = pd.DataFrame(
    similarity, 
    index=matriz_presenca.columns, 
    columns=matriz_presenca.columns
)
df_similarity.head()

id_product,1,2,3,4,5,6,7,8,9,10,...,141,142,143,144,145,146,147,148,149,150
id_product,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.775058,0.737865,0.810191,0.748331,0.769484,0.775058,0.727825,0.711512,0.698771,...,0.795133,0.753819,0.775058,0.769484,0.721605,0.775058,0.872082,0.721605,0.727825,0.775058
2,0.775058,1.000000,0.704295,0.757865,0.714286,0.712931,0.771429,0.750290,0.788811,0.687256,...,0.795192,0.778078,0.771429,0.767772,0.685714,0.742857,0.712931,0.628571,0.750290,0.742857
3,0.737865,0.704295,1.000000,0.800641,0.704295,0.865181,0.732467,0.712396,0.777778,0.707107,...,0.675923,0.739795,0.732467,0.757033,0.704295,0.788811,0.729996,0.732467,0.739795,0.704295
4,0.810191,0.757865,0.800641,1.000000,0.757865,0.753310,0.757865,0.789747,0.773953,0.735980,...,0.831239,0.789747,0.730798,0.779287,0.730798,0.730798,0.805263,0.757865,0.763422,0.757865
5,0.748331,0.714286,0.704295,0.757865,1.000000,0.795192,0.742857,0.694713,0.760639,0.627495,...,0.795192,0.722501,0.714286,0.685511,0.685714,0.714286,0.767772,0.657143,0.722501,0.714286

In [20]:
# Determinação para produto alvo
produto_alvo = 27
# Atribuição para organizar os valores de similaridade em função do produto alvo
similares = df_similarity[produto_alvo].sort_values(ascending=False)

In [21]:
# Leitura da tabela de produtos tratados e renomeação da coluna 'code' para 'id_product'
df_produtos = pd.read_csv('CSVs_tratados/produtos_tratados.csv', sep=';')
df_produtos.rename(columns={'code':'id_product'}, inplace=True)
df_produtos.head()

                             name     price  id_product actual_category
0     Transponder AIS Maré Magnum  33122.52           1     eletrônicos
1       Transponder Furuno Marlin  13998.15           2     eletrônicos
2    Radar Furuno Pulse Leviathan   9024.19           3     eletrônicos
3       Rádio AIS Hydro Tidal Zen   3381.88           4     eletrônicos
4  Piloto Automático Furuno Storm  23669.01           5     eletrônicos

In [22]:
# Junção e Exibição das tabelas com valor de similaridade e produtos
df_final = pd.merge(similares, df_produtos, on='id_product')
df_final.rename(columns={27:'similaridade'},inplace=True)
df_final.head()

,id_product,similaridade,name,price,actual_category
0,27,1.000000,GPS Garmin Vortex Maré Drift,16511.45,eletrônicos
1,94,0.869626,Motor de Popa Volvo Magnum 276HP,40750.84,propulsão
2,11,0.868037,GPS Furuno Swift Leviathan Poseidon,36231.91,eletrônicos
3,35,0.853913,Radar Furuno Swift,11005.53,eletrônicos
4,115,0.850000,Cabo de Nylon Delta Force Magnum Leviathan,830.59,ancoragem

In [23]:
# Exibição dos 5 produtos que mais são comprados com o produto alvo GPS Garmin Vortex Maré Drift
print(f"Produtos que costumam sair junto com o product_id {produto_alvo}:")
df_final.iloc[0:6]

Produtos que costumam sair junto com o product_id 27:

,id_product,similaridade,name,price,actual_category
0,27,1.000000,GPS Garmin Vortex Maré Drift,16511.45,eletrônicos
1,94,0.869626,Motor de Popa Volvo Magnum 276HP,40750.84,propulsão
2,11,0.868037,GPS Furuno Swift Leviathan Poseidon,36231.91,eletrônicos
3,35,0.853913,Radar Furuno Swift,11005.53,eletrônicos
4,115,0.850000,Cabo de Nylon Delta Force Magnum Leviathan,830.59,ancoragem
5,1,0.850000,Transponder AIS Maré Magnum,33122.52,eletrônicos