In [37]:
import pandas as pd
import numpy as np

df = pd.read_csv("datasets/produtos_raw.csv")
df

,name,price,code,actual_category
0,Transponder AIS Maré Magnum,R$ 33122.52,1,ELETRONICOS
1,Transponder Furuno Marlin,R$ 13998.15,2,ELETRONICOS
2,Radar Furuno Pulse Leviathan,R$ 9024.19,3,E L E T R Ô N I C O S
3,Rádio AIS Hydro Tidal Zen,R$ 3381.88,4,Eletrunicos
4,Piloto Automático Furuno Storm,R$ 23669.01,5,Eletronicoz
...,...,...,...,...
152,Corrente Delta Vox Ion,R$ 495.98,146,ancoragem
153,Corrente Danforth Force Leviathan Impulse,R$ 3030.08,147,Ancoraguem
154,Âncora Delta Force Barracuda Mako,R$ 4785.56,148,Ancorajem
155,Cabo de Nylon Bruce Core,R$ 1163.62,149,Ancoragem
156,Cabo de Nylon Danforth Magnum Vox,R$ 1645.66,150,Ancorajem

In [48]:
df['price'] = df['price'].str.replace('R$', '',regex=False).astype('float64')
df['price']

0      33122.52
1      13998.15
2       9024.19
3       3381.88
4      23669.01
         ...
152      495.98
153     3030.08
154     4785.56
155     1163.62
156     1645.66
Name: price, Length: 157, dtype: float64

In [ ]:
df['actual_category'] = df['actual_category'].str.lower().str.replace(' ','')
df['actual_category']

                                          name     price  code actual_category
0                  Transponder AIS Maré Magnum  33122.52     1     eletronicos
1                    Transponder Furuno Marlin  13998.15     2     eletronicos
2                 Radar Furuno Pulse Leviathan   9024.19     3     eletrônicos
3                    Rádio AIS Hydro Tidal Zen   3381.88     4     eletrunicos
4               Piloto Automático Furuno Storm  23669.01     5     eletronicoz
..                                         ...       ...   ...             ...
152                     Corrente Delta Vox Ion    495.98   146       ancoragem
153  Corrente Danforth Force Leviathan Impulse   3030.08   147      ancoraguem
154          Âncora Delta Force Barracuda Mako   4785.56   148       ancorajem
155                   Cabo de Nylon Bruce Core   1163.62   149       ancoragem
156          Cabo de Nylon Danforth Magnum Vox   1645.66   150       ancorajem

[157 rows x 4 columns]

In [ ]:
condicoes = [
    df['actual_category'].str.contains('eletr'),
    df['actual_category'].str.contains('pro'),
    df['actual_category'].str.contains('anco'),
]

normalizada = ['eletrônicos', 'propulsão', 'ancoragem']

In [35]:
df['coluna_normalizada'] = np.select(condicoes, normalizada, default='Outros')
print(df['coluna_normalizada'].value_counts())

coluna_normalizada
propulsão      53
ancoragem      53
eletrônicos    51
Name: count, dtype: int64

In [32]:
df['coluna_normalizada'] == 'Outros'
df

,name,price,code,actual_category,coluna_normalizada
0,Transponder AIS Maré Magnum,R$ 33122.52,1,eletronicos,eletrônicos
1,Transponder Furuno Marlin,R$ 13998.15,2,eletronicos,eletrônicos
2,Radar Furuno Pulse Leviathan,R$ 9024.19,3,eletrônicos,eletrônicos
3,Rádio AIS Hydro Tidal Zen,R$ 3381.88,4,eletrunicos,eletrônicos
4,Piloto Automático Furuno Storm,R$ 23669.01,5,eletronicoz,eletrônicos
...,...,...,...,...,...
152,Corrente Delta Vox Ion,R$ 495.98,146,ancoragem,ancoragem
153,Corrente Danforth Force Leviathan Impulse,R$ 3030.08,147,ancoraguem,ancoragem
154,Âncora Delta Force Barracuda Mako,R$ 4785.56,148,ancorajem,ancoragem
155,Cabo de Nylon Bruce Core,R$ 1163.62,149,ancoragem,ancoragem
156,Cabo de Nylon Danforth Magnum Vox,R$ 1645.66,150,ancorajem,ancoragem

In [33]:
df_outros = df[df['coluna_normalizada']=='Outros']
df_outros

,name,price,code,actual_category,coluna_normalizada
106,Âncora Delta Swift,R$ 1789.19,103,encoragem,Outros
113,Corrente Bruce Current,R$ 2495.51,110,encoragem,Outros
116,Âncora Delta Mako Ultra,R$ 4394.96,113,encoragem,Outros
131,Cabo de Nylon Delta Velocity Core Mako,R$ 1549.35,127,encoragem,Outros
132,Cabo de Nylon Delta Velocity Core Mako,R$ 1549.35,127,encoragi,Outros
133,Boia de Arqueamento Bruce Marlin Hydra,R$ 4650.72,128,encoragem,Outros