In [ ]:
import pandas as pd

df = pd.read_json("datasets/custos_importacao.json")
df_explode_historic = df.explode('historic_data').reset_index(drop=True)

,product_id,product_name,category,historic_data
0,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '10/08/2016', 'usd_price': 1058..."
1,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '15/06/2018', 'usd_price': 8778..."
2,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '25/09/2018', 'usd_price': 8023..."
3,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '19/03/2019', 'usd_price': 8772..."
4,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '17/01/2020', 'usd_price': 7918..."
...,...,...,...,...
1255,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '01/06/2023', 'usd_price': 326.88}"
1256,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '31/01/2024', 'usd_price': 332.26}"
1257,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '29/08/2024', 'usd_price': 292.03}"
1258,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '04/10/2024', 'usd_price': 300.96}"
1259,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '25/10/2024', 'usd_price': 288.9}"

In [ ]:
df_historic_data = pd.json_normalize(df_explode_historic['historic_data'])

,product_id,product_name,category,historic_data
0,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '10/08/2016', 'usd_price': 1058..."
1,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '15/06/2018', 'usd_price': 8778..."
2,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '25/09/2018', 'usd_price': 8023..."
3,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '19/03/2019', 'usd_price': 8772..."
4,1,Transponder AIS Maré Magnum,eletrônicos,"{'start_date': '17/01/2020', 'usd_price': 7918..."
...,...,...,...,...
1255,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '01/06/2023', 'usd_price': 326.88}"
1256,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '31/01/2024', 'usd_price': 332.26}"
1257,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '29/08/2024', 'usd_price': 292.03}"
1258,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '04/10/2024', 'usd_price': 300.96}"
1259,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,"{'start_date': '25/10/2024', 'usd_price': 288.9}"

In [15]:
df_final = pd.concat([df_explode_historic.drop('historic_data', axis=1), df_historic_data], axis=1)

In [16]:
df_final['start_date'] = pd.to_datetime(df_final['start_date'], dayfirst=True)

In [24]:
df_final['product_name'].astype(object)

0             Transponder AIS Maré Magnum
1             Transponder AIS Maré Magnum
2             Transponder AIS Maré Magnum
3             Transponder AIS Maré Magnum
4             Transponder AIS Maré Magnum
                      ...
1255    Cabo de Nylon Danforth Magnum Vox
1256    Cabo de Nylon Danforth Magnum Vox
1257    Cabo de Nylon Danforth Magnum Vox
1258    Cabo de Nylon Danforth Magnum Vox
1259    Cabo de Nylon Danforth Magnum Vox
Name: product_name, Length: 1260, dtype: object

In [25]:
df_final.to_csv('custo_importacao.csv', index=False, sep=";", encoding='utf-8-sig')
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1260 non-null   int64
 1   product_name  1260 non-null   str
 2   category      1260 non-null   str
 3   start_date    1260 non-null   datetime64[us]
 4   usd_price     1260 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 49.3 KB