In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../datasets/produtos_raw.csv")
df

,name,price,code,actual_category
0,Transponder AIS Maré Magnum,R$ 33122.52,1,ELETRONICOS
1,Transponder Furuno Marlin,R$ 13998.15,2,ELETRONICOS
2,Radar Furuno Pulse Leviathan,R$ 9024.19,3,E L E T R Ô N I C O S
3,Rádio AIS Hydro Tidal Zen,R$ 3381.88,4,Eletrunicos
4,Piloto Automático Furuno Storm,R$ 23669.01,5,Eletronicoz
...,...,...,...,...
152,Corrente Delta Vox Ion,R$ 495.98,146,ancoragem
153,Corrente Danforth Force Leviathan Impulse,R$ 3030.08,147,Ancoraguem
154,Âncora Delta Force Barracuda Mako,R$ 4785.56,148,Ancorajem
155,Cabo de Nylon Bruce Core,R$ 1163.62,149,Ancoragem
156,Cabo de Nylon Danforth Magnum Vox,R$ 1645.66,150,Ancorajem

In [3]:
df['price'] = df['price'].str.replace('R$', '',regex=False).astype('float64')
df['price']

0      33122.52
1      13998.15
2       9024.19
3       3381.88
4      23669.01
         ...
152      495.98
153     3030.08
154     4785.56
155     1163.62
156     1645.66
Name: price, Length: 157, dtype: float64

In [4]:
df['actual_category'] = df['actual_category'].str.lower().str.replace(' ','')
df['actual_category']

0      eletronicos
1      eletronicos
2      eletrônicos
3      eletrunicos
4      eletronicoz
          ...
152      ancoragem
153     ancoraguem
154      ancorajem
155      ancoragem
156      ancorajem
Name: actual_category, Length: 157, dtype: str

In [8]:
condicoes = [
    df['actual_category'].str.contains('eletr'),
    df['actual_category'].str.contains('pro'),
    df['actual_category'].str.contains('anco|enc'),
]

normalizada = ['eletrônicos', 'propulsão', 'ancoragem']

In [9]:
df['coluna_normalizada'] = np.select(condicoes, normalizada, default='Outros')
print(df['coluna_normalizada'].value_counts())

coluna_normalizada
propulsão      53
ancoragem      53
eletrônicos    51
Name: count, dtype: int64

In [12]:
df['coluna_normalizada'] == 'Outros'
df.info()
df_final = df.drop_duplicates()
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                157 non-null    str
 1   price               157 non-null    float64
 2   code                157 non-null    int64
 3   actual_category     157 non-null    str
 4   coluna_normalizada  157 non-null    str
dtypes: float64(1), int64(1), str(3)
memory usage: 6.3 KB
<class 'pandas.DataFrame'>
Index: 155 entries, 0 to 156
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                155 non-null    str
 1   price               155 non-null    float64
 2   code                155 non-null    int64
 3   actual_category     155 non-null    str
 4   coluna_normalizada  155 non-null    str
dtypes: float64(1), int64(1), str(3)
memory usage: 7.3 KB

Empty DataFrame
Columns: [name, price, code, actual_category, coluna_normalizada]
Index: []